### PR TITLE
Dockerfile as well as custom config cmdline argument

### PR DESCRIPTION
**Pull request by michael-robbins**
Adding in Dockerfile as well as ability to use custom configs in solaiot.py

For instance, this will use the config-example.py file:
```
./solariot.py --config config-example
```

Also provided a basic Dockerfile that can be used to build a working copy as well

### CODE REVIEW

**Comment by michael-robbins** [comment]
I'll leave it for another PR, but I've revamped the CLI args to handle log levels and updated solariot.py to log correctly for what levels are active as well as reformatting to make the code more python 3-ish.

Can also help setup github actions as well if you want to produce Docker images/pypi releases/linting on PRs/etc!

**Comment by meltaxa** [comment]
Thanks for the PR submission @michael-robbins. I've put it in my queue for review. Also interested in your ideas for the Github Actions. I don't personally use Docker for Solariot, but there is indeed dockerized forks of this project. Makes sense to have this option.

**Comment by michael-robbins** [comment]
Github Actions can be used to add things like a linter to all PRs, build packages for pypi, build and push Docker images!

An example of a linter could be something like this: https://github.com/emojirades/emojirades/blob/master/.github/workflows/ci.yml

Where each commit for any branch is linted and pytest is run over it for instance!

**Comment by michael-robbins** [comment]
I'd prefer to help dockerise the upstream repo than have to use someone elses fork and miss out on any good stuff from upstream (or maintain my own, which I kinda am now locally)

**Comment by scottah** [comment]
@michael-robbins is there a particular mount I need to make when running the image to get it to see my config.py ? 

If I try to to mount my local directory containing config.py to /solariot in the container it then fails to find solariot.py to run.

Perhaps if you're able to share your docker run command ? 
Am reasonably new to Docker, so am probably missing something basic.... thanks!

**Comment by meltaxa** [comment]
Hi @scottah, check out the [README](https://github.com/meltaxa/solariot/blob/master/README.md) which has the Docker instructions you are looking for.

**Comment by scottah** [comment]
Ah, had the old readme, got it, thanks!

**Comment by michael-robbins** [comment]
Yeah, I'm being a bit sneakier and just bind mounting in `/solariot/config.py` directly (not a folder or anything) and doing `solariot.py --config config` to reference the config file!

**Comment by michael-robbins** [comment]
At some point in the future I'd like to just be able to specify the individual config file (instead of the 'python file to import in') and use like YAML or something, but ehh, currently it works fine :)

**Pull request merged**
